#!/usr/bin/env python3

import argparse
import sys
import os
import json
import resourceGen as rg
import cachetime as ct
import manipulation as man
import pods
from utils import *

actions = {
    'create': rg.create_resources,
    'c': rg.create_resources,
    'delete': rg.delete_resources,
    'd': rg.delete_resources,
    'get': rg.get_resources,
    'g': rg.get_resources,
    'restart': ct.delete_manager,
    'r': ct.delete_manager,
    'getlogs': ct.get_logs,
    'gl': ct.get_logs,
    'getcache': ct.restart_all_gc,
    'gc': ct.restart_all_gc,
    'manipulate': man.manipulate,
    'm': man.manipulate,
    'getstatus': rg.get_vnic_status,
    'gs': rg.get_vnic_status,
    'describe': rg.describe_resources,
    'des': rg.describe_resources,
    'cvsistress' : rg.cvsi_stresstest,
    'cst' : rg.cvsi_stresstest,
    'getinfo': pods.get_pod_info,
    'gi': pods.get_pod_info,
    'changeimage': pods.update_deployment_image,
    'ci': pods.update_deployment_image,
    'getmetrics': pods.get_pod_metrics,
    'gm': pods.get_pod_metrics,
    'watch': pods.watch_pods,
    'w': pods.watch_pods,
    'trace': pods.trace_logs,
    't': pods.trace_logs,
    'stat': rg.get_resource_status,
    'leaks': rg.detect_leaks,
    'lk': rg.detect_leaks,
    'removefinal': rg.force_delete_objects,
    'rf': rg.force_delete_objects
}

def get_parser():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description='''
Network-Resource-Simulator is a powerful tool for simulating and managing network objects in a Kubernetes environment. 
It is designed for testing and development, providing a comprehensive suite of commands to create, delete, and manipulate various network resources.

Here are the main actions you can perform:
------------------------------------------
  c, create         - Create network resources like Routers, SGs, Networks, VNICs, LBs etc.
  d, delete         - Delete network resources from the specified namespace.
  r, restart        - Restart a Manager/All the managers.
  gl, getlogs       - Get logs from the existing managers/Restarted manager, Also gets the cache information from them.
  gc, getcache      - Get Cache information directly by restarting all the managers.
  m, manipulate     - Mimic the production environment by randomly create/update/delete various resources.
  g, get            - Get the created resources from the given namespace.
  gs, getstatus     - Get the status of the created VNICs.
  des, describe     - Describe a specific resource type from the given namespace.
  cst, cvsistress   - Perform a stress test on the CVSI resources.
  gi, getinfo       - Get the image information of the manager pods.
  ci, changeimage   - Change the image of the manager pods to a new tag or revert to a previous one.
  gm, getmetrics    - Fetch and display metrics from manager pods, with an optional grep pattern for filtering.
  w, watch          - Continuously monitor and display the status of manager pods.
  stat              - Get the status of a specific resource type from the given namespace.
  lk, leaks         - Run the leak detection script to find leaked net-core objects.
  rf, removefinal   - Force-delete objects stuck in 'Terminating' state by removing their finalizers in K8S side. Can optionally target a specific resource [target].

Notes:
------------------------------------------
  **Stateful Creation:** The `create` command is stateful. It tracks the last used VPC index
  in a hidden file (`.nrs_state_file.txt`) to prevent IP address conflicts on subsequent runs.
  To reset the counter, manually delete this file after ensuring the namespace is clean.

  **Configuration File:** If `config.json` is present, the script will offer to use it,
  allowing for execution without command-line arguments.

  **Image Management:** The `changeimage` command depends on `./scripts/gen_deployment.py`
  and creates `deployment.yaml.bak`. The `--revert` flag uses this file to undo the last change.

  **Resource Tracking:** The `manipulate` and `delete --deletefromfile` actions require the
  `applied_resources.txt` file, which is generated by the `create` command.
'''
    )
    parser.add_argument('action', nargs='?', default=None, help="The main action to be performed. Choose from the list above.")
    parser.add_argument('resource_type', nargs='?', default=None, help="For 'des'/'stat'/'rf' actions: the resource type. For 'trace': the search term.")

    parser.add_argument('-e', '--environment', choices=['region-1', 'region-2'], default='region-1', help="Specify the target environment (region-1 or region-2). Default is 'region-1'.")
    parser.add_argument('-ns', '--namespace', default='sim-resources', help="The Kubernetes namespace for resource creation/deletion. Default is 'sim-resources'.", dest="namespace")
    parser.add_argument('-nc', '--networkcount', type=int, default=1, help="Number of networks to create per VPC. (For 'create' action only)")
    parser.add_argument('-ec', '--endpointcount', type=int, default=1, help="Number of endpoints to create per network. (For 'create' action only)")
    parser.add_argument('-ripc', '--reservedipcount', type=int, default=1, help="Number of Reserved IPs to create. Requires '-vni' flag. (For 'create' action only)", dest="ripcount")
    parser.add_argument('-n', '--num', type=int, default=1, help="Number of VPCs to create. (For 'create' action only & MAX ~65k VPCs ;))", dest="sets")
    parser.add_argument('-lb', '--loadbalancer', action='store_true', help="Include load balancers in the resource creation. (For 'create' action only)")
    parser.add_argument('-epgw', '--endpointgateway', type=int, nargs='?', const=1, default=0, help="Number of Endpoint Gateways to create. Use without a number for 1.", dest="epgwcount")
    parser.add_argument('-sy', '--saveyaml', action='store_true', help="Save the generated Kubernetes YAML files for debugging. (For 'create' action only)", dest="saveyaml")
    apply_group = parser.add_mutually_exclusive_group()
    apply_group.add_argument('-a', '--apply', action='store_true', help="Generate YAML files without applying them to the cluster. (For 'create' action only)", dest="apply")
    apply_group.add_argument('-ba', '--batch-apply', action='store_true', help="Create and apply resources in efficient batches for faster creation. (For 'create' action only)", dest="batchapply")
    apply_group.add_argument('-pa', '--parallel-apply', type=int, nargs='?', const=os.cpu_count(), default=None, help="Create and apply resources with parallel application (sequential generation). (For 'create' action only)", dest="parallel")
    apply_group.add_argument('-fp', '--fully-parallel', type=int, nargs='?', const=os.cpu_count(), default=None, help="Create resources with fully parallel generation and application for maximum speed. (For 'create' action only)", dest="fullyparallel")
    parser.add_argument('-dff', '--deletefromfile', action='store_true', help="Delete resources listed in the 'applied_resources.txt' file. (For 'delete' action only)", dest="delcurr")
    parser.add_argument('-i', '--interactive', action='store_true', help="Enable interactive mode for deleting resources. (For 'delete' action only)", dest="interactive")
    parser.add_argument('-f', '--force', action='store_true', help="Force delete resources without confirmation. (For 'delete' action only)", dest="force_delete")
    parser.add_argument('-y', '--yes', action='store_true', help="Assume \'yes\' to all confirmation prompts. (For 'delete' action only)")
    parser.add_argument('-cn', '--containername', default='core-manager', choices=['core-manager', 'net-manager'], help="Specify the container name for 'restart' or 'getlogs' actions. Default is 'core-manager'.", dest="containername")
    parser.add_argument('-sn', '--specificnode', nargs='+', help="Specify one or more node names to create VNIC resources on. (For 'create' action only)", dest="specificnode")
    parser.add_argument('-en', '--excludenode', nargs='+', help="Specify one or more node names to exclude from VNIC creation. (For 'create' action only)", dest="excludenode")
    parser.add_argument('-parc', '--publicaddressrangecount', type=int, default=0, help="Number of public address ranges to create. (For 'create' action only)", dest="parcount")
    parser.add_argument('-vni', '--vnitype', choices=['smt', 'cvsi', 'xacc', 'base'], nargs='?', const='base', default=None, help="Specify the VNI type for creation (smt: ShareMountTarget, cvsi: ClusterVSI, xacc: Cross-Account VNI, base: default VNI).", dest="vnitype")
    parser.add_argument('-xacc-ns', type=str, default='xacc-ns', help="Namespace for the cross-account VNI when using '-vni xacc'. Defaults to 'xacc-ns'.", dest="xacc_namespace")
    parser.add_argument('-nn', '--nep-nif', action='store_true', help="Create NEP and NIF directly, skipping VNIC creation.", dest="nep_nif")
    parser.add_argument('-fl', '--flowlog', nargs='?', const='Router', help="Include FlowLog resources. Target can be Router (default), Network, VirtualNic (alias: vnic), or VirtualNetworkInterface (alias: vni). Creates one FlowLog per target instance.", dest="flowlogs")
    parser.add_argument('-inp', '--included-protocols', type=int, nargs='+', help="List of included IPv4 protocols (0-255).", dest="included_protocols")
    parser.add_argument('-exp', '--excluded-protocols', type=int, nargs='+', help="List of excluded IPv4 protocols (0-255).", dest="excluded_protocols")
    parser.add_argument('-one', '--only-one', action='store_true', help="Limit FlowLog creation to just one instance, regardless of the number of targets.", dest="flowlog_one")
    parser.add_argument('--file', type=str, default=None, help="Output the 'trace' results to a specified file.", dest="output_file")
    parser.add_argument('--pod', type=str, default=None, help="Specify a single pod name to trace logs from (skips interactive selection).", dest="pod_name")
    image_group = parser.add_mutually_exclusive_group()
    image_group.add_argument('--tag', type=str, help="The new image tag to apply for the 'changeImage' action.")
    image_group.add_argument('--revert', action='store_true', help="Revert to the previously backed-up image for the 'changeImage' action.")
    parser.add_argument('--only', type=str, choices=['core-manager', 'net-manager', 'edge-manager', 'clean-manager'], help="Optionally update only a specific manager's image. Use with --tag. Note: 'core-manager' and 'edge-manager' share the same image, so selecting either will update both.")
      
    return parser
  
if __name__ == "__main__":
    parser = get_parser()
    args = None

    # If command-line arguments are provided, use them.
    if len(sys.argv) > 1:
        args = parser.parse_args()
    # If no command-line arguments, try to use the config file.
    else:
        config_path = 'config.json'
        if os.path.exists(config_path):
            print_yellow(f"Found configuration file: '{config_path}'.")
            with open(config_path, 'r') as f:
                config_data = json.load(f)
            
            print_green("\n--- Configuration from config.json ---")
            for section, params in config_data.items():
                if section == "description":
                    continue
                if isinstance(params, dict):
                    print_green(f"\n[{section.replace('_', ' ').title()}]")
                    for key, value in params.items():
                        print(f"  {key:<25}: {value}")
            print_green("\n--------------------------------------")

            proceed = input("Do you want to proceed with this configuration? (y/n): ").lower()
            if proceed in ['y', 'yes']:
                args = load_and_process_config(parser, config_path)
            else:
                print_green("\nOperation cancelled. Please provide command-line arguments to run the tool.")
                parser.print_help()
                sys.exit(0)
        else:
            print_green("\nWelcome to the Net Object Simulator!")
            print_green("To get started, run the script with command-line arguments, or create a 'config.json' file.")
            parser.print_help()
            sys.exit(0)

    # Final check to ensure an action is set
    if not args.action:
        print_red("Error: An 'action' must be specified either in 'config.json' or as a command-line argument.")
        parser.print_help()
        sys.exit(1)

    ns = args.namespace

    args = checking_mode_for_epgw(args)
    args = checking_mode_for_nep_nif(args)

    # If creating a large number of resources, suggest using batch-apply for speed.
    if args.action in ['create', 'c'] and args.apply and not args.batchapply and not args.parallel and args.sets > 10:
        print_yellow("You are about to create more than 10 VPCs with the standard apply method, which can be very slow.")
        print_green("For significantly faster creation, I recommend using the 'batch-apply' or 'parallel' method.")
        
        try:
            switch_to_batch = input("Would you like to switch to batch-apply for this run? (y/n): ").lower()
            if switch_to_batch in ['y', 'yes']:
                print_green("Switching to batch-apply mode...")
                args.batchapply = True
                args.apply = False
            else:
                print_yellow("Proceeding with standard apply...")
        except KeyboardInterrupt:
            print_yellow("\nOperation cancelled by user.")
            sys.exit(1)

    # Validate incompatible arguments
    if args.action in ['create', 'c'] and args.vnitype is not None:
        if args.networkcount > 1 or args.endpointcount > 1:
            print_red("Error: The --vnitype (-vni) flag cannot be used with --networkcount (-nc) or --endpointcount (-ec) greater than 1.")
            print_yellow("This combination is not supported. Please run with default values (-nc 1, -ec 1) when using a VNI type.")
            sys.exit(1)

    # Main execution block. Calls appropriate function based on the action.
    try: 
        action_function = actions.get(args.action)
        if not action_function:
            print_red(f"Error: Invalid action '{args.action}'.")
            parser.print_help()
            sys.exit(1)

        if args.action in ['create', 'c']:
            action_function(ns, args)
        elif args.action in ['des', 'describe', 'stat']:            
            if not args.resource_type:
                parser.error(f"the '{args.action}' action requires a resource_type to be specified.")
            action_function(ns, args.resource_type)
        elif args.action in ['rf', 'removefinal']:
            if not args.resource_type:
                parser.error(f"the '{args.action}' action requires a resource_type to be specified.")
            action_function(ns, args.resource_type)
        elif args.action in ['get', 'g', 'gs', 'getstatus']:
            action_function(ns)
        elif args.action in ['cvsistress', 'cst']:
            action_function(ns, args)
        elif args.action in ['delete', 'd']:
            if args.delcurr:
                rg.deleteCurrentResources("applied_resources.txt", args)
            elif args.force_delete:
                rg.deleteResourcesForce(ns, args)
            elif args.interactive:
                rg.deleteResourcesInteractive(ns)
            else:
                action_function(ns, args)
        elif args.action in ['restart', 'r', 'getlogs', 'gl', 'getcache', 'gc']:
            ct.setup()
            action_function()
        elif args.action in ['m', 'manipulate']:
            action_function(args)
        elif args.action in ['t', 'trace']:
            if not args.resource_type:
                print_red("Error: 'trace' requires a search term. Usage: ./netsim.py trace <SEARCH_TERM>")
                sys.exit(1)
            action_function(args.resource_type, args.output_file, args.pod_name)
        elif args.action in ['getImage', 'gi', 'watch', 'w', 'leaks', 'lk']:
            action_function()
        elif args.action in ['getmetrics', 'gm']:
            action_function()
        elif args.action in ['changeimage', 'ci']:
            if args.revert and args.only:
                parser.error("the --only flag cannot be used with --revert.")
            if not args.tag and not args.revert:
                print_red("Error: 'changeimage' requires either --tag or --revert.")
                sys.exit(1)
            action_function(tag=args.tag, revert=args.revert, only=args.only)

    except RuntimeError as e:
        print_red(f"\nAn unrecoverable error occurred during the batch operation: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        print_yellow("\nOperation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print_red(f"An unexpected error occurred: {e}")
        sys.exit(1)
